name: papermark
region: fra1
services:
- name: web
  github:
    repo: art-of-x/papermark
    branch: main
    deploy_on_push: false
  build_command: npm run build
  run_command: npm run start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
    type: GENERAL
  - key: NEXTAUTH_URL
    value: https://documents.art-of-x.com
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: NEXT_PUBLIC_BASE_URL
    value: https://documents.art-of-x.com
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: NEXT_PUBLIC_MARKETING_URL
    value: https://documents.art-of-x.com
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: NEXT_PUBLIC_APP_BASE_HOST
    value: documents.art-of-x.com
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: NEXT_PUBLIC_UPLOAD_TRANSPORT
    value: vercel
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: NEXTAUTH_SECRET
    value: ${APP_SECRET}
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXT_PRIVATE_DOCUMENT_PASSWORD_KEY
    value: ${DOCUMENT_PASSWORD_SECRET}
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DATABASE_URL
    value: ${papermark-db.DATABASE_URL}
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: POSTGRES_PRISMA_URL
    value: ${papermark-db.DATABASE_URL}
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
  - key: POSTGRES_PRISMA_URL_NON_POOLING
    value: ${papermark-db.DATABASE_URL}
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
jobs:
- name: db-migrate
  kind: PRE_DEPLOY
  github:
    repo: art-of-x/papermark
    branch: main
  environment_slug: node-js
  run_command: ./node_modules/.bin/prisma db push --accept-data-loss --skip-generate
  envs:
  - key: DATABASE_URL
    value: ${papermark-db.DATABASE_URL}
    scope: RUN_TIME
    type: GENERAL
  - key: POSTGRES_PRISMA_URL
    value: ${papermark-db.DATABASE_URL}
    scope: RUN_TIME
    type: GENERAL
  - key: POSTGRES_PRISMA_URL_NON_POOLING
    value: ${papermark-db.DATABASE_URL}
    scope: RUN_TIME
    type: GENERAL
databases:
- name: papermark-db
  engine: PG
  version: "16"
  production: false
